# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: go_dokku

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@170.187.163.225:22/server1'
          ssh_private_key: '${{ secrets.SSH_PRIVATE_KEY }}'
          secrets: |
            APM_TOKEN
        env:
            ELASTIC_APM_SECRET_TOKEN: "${{ secrets.APM_TOKEN }}"
            ELASTIC_APM_SERVER_URL: "https://af5fa4e4cf0f41ea957b815e9d6626fe.apm.southamerica-east1.gcp.elastic-cloud.com:443"
          
          
